name: Create Azure Resources

on:
  push:
    paths:
      - 'infra/**'
      - '.github/workflows/createAzureResources.yml'
  workflow_dispatch:    

jobs:
  create-azure-resources:
    
    env:
        LOCATION: 'canadacentral'

    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Publisher Email
        run: echo "PUBLISHER_EMAIL=${{ secrets.PUBLISHER_EMAIL }}" >> $GITHUB_ENV

      - name: createResources
        id: createResources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          scope: subscription
          region: ${{ env.LOCATION }}
          deploymentName:  ${{ github.run_id }}
          template: ./infra/main.bicep
          parameters: ./infra/main.bicepparam
            
      - uses: gliech/create-github-secret-action@v1
        with:
          name: APIM_NAME
          value: ${{ steps.createResources.outputs.apimName }}
          pa_token: ${{ secrets.PA_TOKEN }}        
      
      - uses: gliech/create-github-secret-action@v1
        with:
          name: FIBO_API_NAME
          value: ${{ steps.createResources.outputs.fiboApiName }}
          pa_token: ${{ secrets.PA_TOKEN }}

      - name: Test Output
        run: echo ${{ steps.createResources.outputs.fibiApiUrl }}