name: Deploy Fibonaci Web Api

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/deployApi.yml'
  workflow_dispatch: 

env:
  AZURE_WEBAPP_PACKAGE_PATH: './src/FibonacciApi'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x'           # set this to the dot net version to use  
  LOCATION: 'canadacentral'
  
jobs:
  build-and-deploy-api:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release --property:PublishDir='./myapp' 
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v3
        with: 
          app-name: ${{ secrets.FIBO_API_NAME }}          
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

  deploy-api-apim:
    needs: build-and-deploy-api
  
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}      

      - name: Set ApimServiceName
        run: echo "APIM_NAME=${{ secrets.APIM_NAME }}" >> $GITHUB_ENV

      - name: Set ApimServiceName
        run: echo "FIBO_URL=${{ secrets.FIBO_URL }}" >> $GITHUB_ENV
        
      - uses: cschleiden/replace-tokens@v1
        name: Replace Policy variables
        with:
          tokenPrefix: '__'
          tokenSuffix: '__'
          files: '["apis/FibonacciApi/policy.xml"]'
        env:
          tenantid: ${{ secrets.TENANT_ID }}
          audience: ${{ secrets.AUDIENCE_FIBO_API }}

      - name: Deplay FIBO in APIM
        id: createResources
        uses: azure/arm-deploy@v1
        with:                   
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          deploymentName:  ${{ github.run_id }}
          template: ./apis/FibonacciApi/apiMetadata.bicep
          parameters: ./apis/FibonacciApi/apiMetadata.bicepparam        